services:
  # =========================
  # PHP 7.4
  # =========================
  apache74:
    image: httpd:2.4
    ports:
      - ${php73_port:-80}:80
      
    volumes:
      - ${APP_PATH:-./www}:/var/www/html
      - ./apache/vhost.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    
    command: >
      sh -c "sed -i 's/#LoadModule proxy_module/LoadModule proxy_module/' conf/httpd.conf &&
             sed -i 's/#LoadModule proxy_fcgi_module/LoadModule proxy_fcgi_module/' conf/httpd.conf &&
             sed -i 's/#LoadModule setenvif_module/LoadModule setenvif_module/' conf/httpd.conf &&
             echo 'Include conf/extra/httpd-vhosts.conf' >> conf/httpd.conf &&
             httpd-foreground"
  apache83:
    image: httpd:2.4
    deploy:
      replicas: ${start_83:-0}
    ports:
      - "8083:80"
    volumes:
      - ${APP_PATH:-./www}:/var/www/html
      - ./apache/vhost.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    

    command: >
      sh -c "sed -i 's/#LoadModule proxy_module/LoadModule proxy_module/' conf/httpd.conf &&
             sed -i 's/#LoadModule proxy_fcgi_module/LoadModule proxy_fcgi_module/' conf/httpd.conf &&
             sed -i 's/#LoadModule setenvif_module/LoadModule setenvif_module/' conf/httpd.conf &&
             echo 'Include conf/extra/httpd-vhosts.conf' >> conf/httpd.conf &&
             httpd-foreground"

  php74:
    build:
      context: .
      dockerfile: php74.Dockerfile
    container_name: php74_dev
    restart: unless-stopped
    environment:
      - docker_DEV=${docker_DEV}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      #- XDEBUG_MODE=${XDEBUG_MODE}
    volumes:
      - ${APP_PATH:-./www}:/var/www/html/
    extra_hosts:
      - "host.docker.internal:host-gateway"
  php74_xdebug:
    build:
      context: .
      args:
        - XDEBUG_MODE=debug
      dockerfile: php74.Dockerfile
    container_name: php74_dev_xdebug
    restart: unless-stopped
    environment:
      - docker_DEV=${docker_DEV}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - XDEBUG_MODE=${XDEBUG_MODE}
    
    volumes:
      - ${APP_PATH:-./www}:/var/www/html/
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # =========================
  # PHP 8.3
  # =========================
  php83:
    build:
      context: .
      dockerfile: php83.Dockerfile
    container_name: php83_dev
    deploy:
        replicas: ${start_83:-0}
    restart: unless-stopped
    environment:
      - docker_DEV=${docker_DEV}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - XDEBUG_MODE=${XDEBUG_MODE}
    volumes:
      - ${APP_PATH:-./www}:/var/www/html:cached
    extra_hosts:
      - "host.docker.internal:host-gateway"

  php83_xdebug:
    build:
      context: .
      args:
        - XDEBUG_MODE=debug
      dockerfile: php83.Dockerfile
    container_name: php83_dev_xdebug
    deploy:
        replicas: ${start_83:-0}
    restart: unless-stopped
    environment:
      - docker_DEV=${docker_DEV}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - XDEBUG_MODE=${XDEBUG_MODE}
    volumes:
      - ${APP_PATH:-./www}:/var/www/html:cached
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # =========================
  # MySQL
  # =========================
  mysql:
    image: mariadb:10.11
    container_name: mysql_dev
    restart: unless-stopped
    command: --sql-mode="1"
    # MariaDB używa innych nazw zmiennych środowiskowych, 
    # ale zachowuje kompatybilność z MYSQL_*
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data_dev:/var/lib/mysql



  # =========================
  # phpMyAdmin
  # =========================
  pma:
    image: phpmyadmin:latest
    container_name: pma_dev
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
    
  # =========================
  # Redis
  # =========================
  # redis:
  #   image: redis:7
  #   container_name: redis_dev
  #   restart: unless-stopped
  #   ports:
  #     - "6379:6379"
volumes:
  mariadb_data_dev:
