services:
  # =========================
  # PHP 7.4
  # =========================
  php74:
    build:
      context: .
      dockerfile: php74.Dockerfile
    container_name: php74_dev
    restart: unless-stopped
    ports:
      - "8074:80"
    environment:
      - docker_DEV=${docker_DEV}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - XDEBUG_MODE=${XDEBUG_MODE}
    volumes:
      - ${APP_PATH:-./www}:/var/www/html:cached
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # =========================
  # PHP 8.3
  # =========================
  php83:
    build:
      context: .
      dockerfile: php83.Dockerfile
    container_name: php83_dev
    restart: unless-stopped
    ports:
      - "8083:80"
    environment:
      - docker_DEV=${docker_DEV}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - XDEBUG_MODE=${XDEBUG_MODE}
    volumes:
      - ${APP_PATH:-./www}:/var/www/html:cached
    extra_hosts:
      - "host.docker.internal:host-gateway"


  # =========================
  # MySQL
  # =========================
  mysql:
    image: mysql:8.0
    container_name: mysql_dev
    restart: unless-stopped
    # problem z bazÄ… danych
    command: --sql-mode="1"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_db
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_dev:/var/lib/mysql

  # =========================
  # phpMyAdmin
  # =========================
  pma:
    image: phpmyadmin:latest
    container_name: pma_dev
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
    
  # =========================
  # Redis
  # =========================
  redis:
    image: redis:7
    container_name: redis_dev
    restart: unless-stopped
    ports:
      - "6379:6379"
volumes:
  mysql_data_dev:

