services:
  # PHP 7.4
  php74:
    build:
      context: .
      dockerfile: php74.Dockerfile
    container_name: php74_dev
    ports:
      - "8073:8080"
    environment:
      - XDEBUG_MODE=develop,debug
      - XDEBUG_CONFIG=client_host=host.docker.internal start_with_request=yes
    volumes:
      - C:/repo:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # PHP 8.3
  php83:
    build:
      context: .
      dockerfile: php83.Dockerfile
    container_name: php83_dev
    ports:
      - "8083:8080"
    environment:
      - XDEBUG_MODE=develop,debug
      - XDEBUG_CONFIG=client_host=host.docker.internal start_with_request=yes
    volumes:
      - C:/repo:/var/www/html
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # MySQL z zapisem do folderu C:/mysql
  mysql:
    image: mysql:8.0
    container_name: mysql_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_db
    ports:
      - "3306:3306"
    volumes:
      - C:/mysql:/var/lib/mysql  # Mapowanie folderu lokalnego

  # PHPMyAdmin
  pma:
    image: phpmyadmin:latest
    container_name: pma_dev
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
