services:
  # PHP 7.3
  php74:
    build:
      context: .
      dockerfile: php74.Dockerfile
    container_name: php74_dev
    ports:
      - "8074:8080"
    environment:
      - NGINX_WEBROOT=/var/www/html/
      - PHP_MEMORY_LIMIT=512M
      - XDEBUG_MODE=develop,debug
      - XDEBUG_CONFIG=client_host=host.docker.internal start_with_request=yes
    volumes:
      - ./www:/var/www/html  # Ścieżka relatywna do folderu z kodem
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # PHP 8.3
  php83:
    build:
      context: .
      dockerfile: php83.Dockerfile
    container_name: php83_dev
    ports:
      - "8083:8080"
    environment:
      - NGINX_WEBROOT=/var/www/html/
      - PHP_MEMORY_LIMIT=512M
      - XDEBUG_MODE=develop,debug
      - XDEBUG_CONFIG=client_host=host.docker.internal start_with_request=yes
    volumes:
      - ./www:/var/www/html  # Ten sam folder kodu co wyżej
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev_db
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql # Baza danych w podfolderze projektu

  # PHPMyAdmin
  pma:
    image: phpmyadmin:latest
    container_name: pma_dev
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
  # redis
  redis:
  image: redis:7
  container_name: redis_dev
  ports:
    - "6379:6379"
